// Published-page regression: all form submissions and analytics requests are intercepted.
const {chromium,webkit,firefox}=require('playwright'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const live=process.argv[2]==='live',base=live?'https://andreagiaquinto.it':'http://127.0.0.1:8768',out=path.join(process.env.RUNNER_TEMP||'/tmp','plugins-proof');fs.mkdirSync(out,{recursive:true});
const pages=['/','/lezioni-autocad/','/yqarch-italiano/','/express-tools-italiano/','/express-tools-italiano/guida/','/downloads/yqarch/YQArch_Italiano_3.64_GUIDA.html','/privacy/','/404.html'];
const mime={'.html':'text/html','.css':'text/css','.js':'application/javascript','.webp':'image/webp','.avif':'image/avif','.svg':'image/svg+xml'};
let server;if(!live)server=http.createServer((req,res)=>{let file=decodeURIComponent(new URL(req.url,base).pathname);if(file.endsWith('/'))file+='index.html';try{res.writeHead(200,{'Content-Type':mime[path.extname(file)]||'application/octet-stream'});res.end(fs.readFileSync(path.join(process.cwd(),file)));}catch{res.writeHead(404);res.end();}}).listen(8768,'127.0.0.1');
(async()=>{const report=[];try{
for(const[engine,type]of Object.entries({chromium,webkit,firefox})){
 const browser=await type.launch();
 for(const url of pages){const lesson=url==='/lezioni-autocad/';const widths=lesson&&engine==='chromium'?[320,360,375,390,412,430,600,768,800,1024,1366,1440,1920]:[320,1440];
 for(const width of widths){const context=await browser.newContext({viewport:{width,height:900},reducedMotion:'reduce'}),page=await context.newPage(),errors=[],posts=[],google=[];let failReview=true;
 await page.addInitScript(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:async value=>{window.__copied=value;}}}));
 await page.route('**/*',async route=>{const req=route.request(),u=req.url();if(/google-analytics\.com|googletagmanager\.com|googleadservices\.com/.test(u)){google.push(u);return route.fulfill({status:200,body:''});}if(u.includes('cad-bim-preventivi.andrea-giaqui.workers.dev')){if(req.method()==='POST'){posts.push(req.postDataJSON());return route.fulfill({status:failReview?503:200,json:{ok:!failReview}});}return route.fulfill({json:{ok:true,reviews:[],comments:[],nextCursor:null}});}if(!['GET','HEAD','OPTIONS'].includes(req.method()))throw new Error('Unexpected real write');await route.continue();});
 page.on('pageerror',e=>errors.push(e.message));
 const response=await page.goto(base+url,{waitUntil:'networkidle'});assert.equal(response.status(),200);
 const reject=page.getByRole('button',{name:'Rifiuta facoltativi'});if(await reject.isVisible())await reject.click();
 assert.equal(await page.locator('h1').count(),1);assert.equal(await page.locator('.site-footer').count(),1);assert.equal(await page.locator('.sf-nav a').count(),4);assert.equal(await page.locator('.sf-role').innerText(),'Disegnatore CAD e BIM');
 for(const link of await page.locator('.site-footer a,.site-footer button').all()){await link.scrollIntoViewIfNeeded();const b=await link.boundingBox();assert.ok(b&&b.height>=43&&b.x>=-1&&b.x+b.width<=width+1,engine+' '+url+' '+width+' footer control');}
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),engine+' '+width+' '+url+' overflow');
 if(width===320||width===1440){await page.addScriptTag({path:path.join(process.cwd(),'node_modules/axe-core/axe.min.js')});const violations=await page.evaluate(async lesson=>(await axe.run(lesson?document:document.querySelector('.site-footer'),{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}})).violations.map(x=>({id:x.id,nodes:x.nodes.map(n=>n.target)})),lesson);assert.deepEqual(violations,[],engine+' '+url+' '+width);}
 if(engine==='chromium'&&(width===320||width===1440)){const name=url==='/'?'home':url.split('/').filter(Boolean)[0];await page.locator('.site-footer').screenshot({style:'.site-header,.topbar,.skip{visibility:hidden!important}',path:path.join(out,`${live?'live':'candidate'}-shared-${name}-${width}.png`)});}
 if(lesson){await page.locator('.site-footer').scrollIntoViewIfNeeded();await page.waitForFunction(()=>document.querySelector('.mobile-cta').classList.contains('is-hidden'));assert.equal(await page.locator('body').getAttribute('data-build'),'20260930-autocad-v17.10');const form=page.locator('#reviewForm');assert.equal(await form.locator('xpath=ancestor::details').count(),0);assert.ok(await form.isVisible());await form.scrollIntoViewIfNeeded();if(engine==='chromium'&&[320,768,1440].includes(width))await page.locator('.review-details').screenshot({path:path.join(out,`${live?'live':'candidate'}-lesson-reviews-${width}.png`)});
 if(width===320){await page.locator('#reviewName').fill('Verifica Simulata');await page.locator('#reviewText').fill('Test intercettato: nessun messaggio o recensione reale.');await page.locator('#reviewPrivacy').check();await page.locator('#reviewSubmit').click();await page.waitForFunction(()=>document.querySelector('#reviewStatus').textContent.includes('Invio non confermato'));assert.ok((await page.locator('#reviewText').inputValue()).includes('intercettato'));failReview=false;await page.locator('#reviewSubmit').click();await page.waitForFunction(()=>document.querySelector('#reviewStatus').textContent.includes('ricevuta'));assert.equal(posts.length,2);assert.equal(posts[1].source,'autocad-lessons');assert.equal(posts[1].privacy,true);assert.equal(await page.evaluate(()=>(window.dataLayer||[]).filter(x=>['generate_lead','service_quote_success'].includes(x[1])).length),0);}}
 if(url.includes('_GUIDA.html')){assert.equal(await page.locator('.guide-back').getAttribute('href'),'https://andreagiaquinto.it/yqarch-italiano/');await page.locator('#q').fill('YQ_WALL');assert.ok(await page.locator('.card:not(.hide)').count()>0);await page.locator('#clear').click();assert.equal(await page.locator('#q').inputValue(),'');}
 if(url==='/yqarch-italiano/'||url==='/express-tools-italiano/'){assert.equal(await page.locator('body').getAttribute('data-build'),'20260930-plugins-r5');for(const value of ['andrea.giaqui@gmail.com','3337240544']){await page.locator(`[data-copy="${value}"]`).click();assert.equal(await page.evaluate(()=>window.__copied),value);}}
 await page.locator('.site-footer [data-consent-open]').click();assert.ok(await page.getByRole('button',{name:'Rifiuta facoltativi'}).isVisible());await page.getByRole('button',{name:'Rifiuta facoltativi'}).click();assert.deepEqual(google,[]);assert.deepEqual(errors,[]);report.push({engine,width,url,status:'PASS'});await context.close();
 }}await browser.close();}
fs.writeFileSync(path.join(out,(live?'live':'candidate')+'-site-consistency.json'),JSON.stringify(report,null,2));console.log('SITE CONSISTENCY VERIFIED',report.length);
}catch(e){console.error(e);process.exitCode=1;}finally{server?.close();}})();
