import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {submitLesson} from '../cloudflare-worker/src/lessons.js';
import worker from '../cloudflare-worker/src/index.js';
const origin='https://andreagiaquinto.it';
function fixture(){const entries=new Map();const emails=[];const env={SIGNING_SECRET:'isolated-test-secret',EMAIL_FROM:'test@example.invalid',EMAIL_TO:'recipient@example.invalid',QUOTE_FILES:{get:async k=>entries.has(k)?{json:async()=>JSON.parse(entries.get(k))}:null,put:async(k,v)=>entries.set(k,v),list:async({prefix})=>({objects:[...entries.keys()].filter(k=>k.startsWith(prefix)).map(key=>({key})),truncated:false}),delete:async k=>entries.delete(k)}};const deps={json:(body,status)=>Response.json(body,{status}),sendEmail:async(e,p,key)=>{emails.push({payload:p,key});},hmac:async(secret,value)=>createHmac('sha256',secret).update(value).digest('hex'),escapeHtml:s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))};return{entries,emails,env,deps};}
const payload=()=>({requestId:crypto.randomUUID(),name:'Test didattico',email:'test@example.invalid',message:'<script>alert(1)</script>',privacy:true,website:'',source:'autocad-lessons'});
const req=body=>new Request('https://worker.example/api/lessons',{method:'POST',headers:{'Content-Type':'application/json','Origin':origin},body:JSON.stringify(body)});
test('Server validates privacy, address, honeypot and input limits before sending',async()=>{for(const changes of [{privacy:false},{email:'bad'},{website:'spam'},{name:'x'},{message:'x'.repeat(2001)},{requestId:'bad'},{source:'other'}]){const f=fixture();const r=await submitLesson(req({...payload(),...changes}),f.env,origin,f.deps);assert.equal(r.status,400);assert.equal(f.emails.length,0);}});
test('Successful lead has confirmed ID, escaped HTML and one send on retry',async()=>{const f=fixture(),p=payload();let r=await submitLesson(req(p),f.env,origin,f.deps);assert.deepEqual(await r.json(),{ok:true,requestId:p.requestId});assert.equal(f.emails.length,1);assert.ok(f.emails[0].payload.html.includes('&lt;script&gt;'));assert.equal(f.emails[0].key,'autocad-lesson/'+p.requestId);r=await submitLesson(req(p),f.env,origin,f.deps);assert.equal(r.status,200);assert.equal(f.emails.length,1);r=await submitLesson(req({...p,name:'Changed'}),f.env,origin,f.deps);assert.equal(r.status,409);});
test('Provider error does not produce a lead; safe retry reuses idempotency key',async()=>{const f=fixture(),p=payload();let count=0;const keys=[];f.deps.sendEmail=async(e,v,key)=>{keys.push(key);if(count++===0)throw new Error('Unavailable');};let r=await submitLesson(req(p),f.env,origin,f.deps);assert.equal(r.status,503);r=await submitLesson(req(p),f.env,origin,f.deps);assert.equal(r.status,200);assert.equal(keys[0],keys[1]);});
test('Rate limit stops the sixth request',async()=>{const f=fixture();for(let i=0;i<5;i++)assert.equal((await submitLesson(req(payload()),f.env,origin,f.deps)).status,200);assert.equal((await submitLesson(req(payload()),f.env,origin,f.deps)).status,429);assert.equal(f.emails.length,5);});
test('Review listing isolates AutoCAD and exposes only public DTO',async()=>{const f=fixture();f.entries.set('reviews/1',JSON.stringify({displayName:'Anna Rossi',text:'Lezione chiara',service:'Lezioni AutoCAD',status:'approved',email:'never-public@example.invalid'}));f.entries.set('reviews/2',JSON.stringify({displayName:'Mario Bianchi',text:'Servizio render',service:'Render',status:'approved'}));f.entries.set('reviews/3',JSON.stringify({displayName:'Luca Verdi',text:'Da approvare',service:'Lezioni AutoCAD',status:'pending'}));const r=await worker.fetch(new Request('https://worker.example/api/reviews?source=autocad-lessons'),f.env);const d=await r.json();assert.equal(d.reviews.length,1);assert.equal(d.reviews[0].displayName,'Anna R.');assert.equal(d.reviews[0].email,undefined);});
test('Review management GET asks confirmation without changing stored reviews',async()=>{const f=fixture();const id=crypto.randomUUID(),exp=Math.floor(Date.now()/1000)+1000;const signingKey=await crypto.subtle.importKey('raw',new TextEncoder().encode(f.env.SIGNING_SECRET),{name:'HMAC',hash:'SHA-256'},false,['sign']);const signature=await crypto.subtle.sign('HMAC',signingKey,new TextEncoder().encode(`review|${id}|reject|${exp}`));const sig=Buffer.from(signature).toString('base64url');f.entries.set(`reviews-pending/${id}.json`,JSON.stringify({id,displayName:'Test T.',text:'Test review'}));const r=await worker.fetch(new Request(`https://worker.example/api/review-manage?id=${id}&action=reject&exp=${exp}&sig=${sig}`),f.env);assert.equal(r.status,200);assert.ok((await r.text()).includes('method="post"'));assert.ok(f.entries.has(`reviews-pending/${id}.json`));});
